### ISSUE TITLE
NetClient not sending StatusChanged messages?

### ISSUE THREAD

**Issue by ThomasMiz** [TechnologicalPizza/lidgren-network-gen3#3]
NetClient doesn't seem to be giving me any StatusChanged messages, and I can only see whenever the connection status changes through polling client.ConnectionStatus.

This doesn't seem to be a problem in NetServer, where StatusChanged messages seem to be working mostly fine, but sometimes I do get duplicates (ex. two consecutive messages saying "this same NetConnection's status is now Connected")

I made sure that the NetPeer configuration didn't have the message types disabled.

These are the logs on the client's side:
![image](https://user-images.githubusercontent.com/32400648/103243844-ea6e6900-4939-11eb-8b13-e6fb8c3e7bbf.png)

And these are on the server side:
![image](https://user-images.githubusercontent.com/32400648/103243865-f8bc8500-4939-11eb-9eb4-e1d9307db414.png)

Also, what's that error message on the client side? Could it be related to this problem?

**Comment by ThomasMiz** [comment]
Alright so part of the problem was (predictably) my bad (accidentally recycling some messages multiple times). This fixed the status changed messages problem.

But I'm still having an issue where calling NetClient.TryReadMessages(ICollection<...>) throws an exception on [this line](https://github.com/TechnologicalPizza/lidgren-network-gen3/blob/5e5e278fc485949d6967132773fa089d38c4fa31/Lidgren.Network/Memory/NetQueue.cs#L252), where the AsSpan function ends up being AsSpan(2, Math.Min(1, -1)) (head=2, Count=1, _items is an array of four NetIncomingMessage-s where all elements are null except for index 2, which is a Data message).

**Comment by ThomasMiz** [comment]
I also found the reason for the duplicated StatusChanged messages. I was using connection.Status instead of reading the first byte from the message and casting it to a NetConnectionStatus as it should be done [according to this](https://code.google.com/archive/p/lidgren-network-gen3/wikis/IncomingMessageTypes.wiki). I started looking at the property directly because reading that first byte typically gave undefined enum values, and this turned out to be because of [this line right here](https://github.com/TechnologicalPizza/lidgren-network-gen3/blob/5e5e278fc485949d6967132773fa089d38c4fa31/Lidgren.Network/Connection/NetConnection.cs#L134), which should be casting Status to byte:
```cs
info.Write((byte)Status);
```

**Comment by TechPizzaDev** [comment]
My fork actually writes enums as a variable length Int64. 
So writing an enum should be done with `Write<TEnum>()` and reading with `ReadEnum<TEnum>`.
Looking at this I should probably add a `WriteEnum` method for clarity.

**Comment by ThomasMiz** [comment]
I'd keep it as a byte, so other people coming into this fork don't fall into the same annoying trap as I did, but if you wanna keep it as it is tell me and i'll just rever that commit so we can get the NetQueue fix merged

**Comment by TechPizzaDev** [comment]
Maybe a better change would be to write `byte` enums as a byte in `Write<TEnum>`

**Comment by ThomasMiz** [comment]
We can add ```: byte``` to NetConnectionStatus, but we'd have to, whenever we write an enum, check it's size and act accordingly. How would we go around doing such thing efficiently?

**Comment by TechPizzaDev** [comment]
I'm trying to figure something out right now by my current branch has some other changes that make me unable to compile and test right now 😅

**Comment by ThomasMiz** [comment]
Okay, no problem. Let's take a look at this again when you're ready

**Comment by TechPizzaDev** [comment]
Managed to whip this up. Will have to see if it has any performance impact with any hidden allocation or something (it shouldn't have that though). 
```cs
public static void Write<TEnum>(this IBitBuffer buffer, TEnum value
    where TEnum : unmanaged, Enum
{
    switch (value.GetTypeCode())
    {
        case TypeCode.Byte:
            buffer.Write(Unsafe.As<TEnum, byte>(ref value));
            break;

        case TypeCode.SByte:
            buffer.Write(Unsafe.As<TEnum, sbyte>(ref value));
            break;

        case TypeCode.Boolean:
            buffer.Write(Unsafe.As<TEnum, bool>(ref value));
            break;

        default:
            buffer.WriteVar(EnumConverter.ToInt64(value));
            break;
    }
}
```

**Comment by ThomasMiz** [comment]
Okay, I'll revert the commit that added the byte cast so we can merge the rest

**Comment by TechPizzaDev** [comment]
Sadly I have no clue what the client exception may have been or why the connection timed out.
This issue will probably stay open until I merge my current work and investigate that everything is right with status messages.

**Comment by ThomasMiz** [comment]
In my project, I changed the StatusChanged message handling to read an enum and everything is working properly. The error was most probably related to me recycling some messages multiple times, which I've since fixed.

Edit: sorry for accidentally closing the issue. I won't use github through my phone from now, it's way too clumsy.

**Comment by TechPizzaDev** [comment]
Great, the pending work I have should yield in faster reads/writes for enums and strings too.
I suppose you are like a tester/feedback source for me, as I don't really use this library right now, just keeping it fresh for my near-future projects.

**Comment by TechPizzaDev** [comment]
b0c5131 has some fixes though nothing substantial
It would be greatly appreciated if you just pull and check if everything works as I plan to make some substantial changes in the next commits so would want for the current state to be stable @ThomasMiz

**Comment by ThomasMiz** [comment]
@TechnologicalPizza My application is pretty barebones right now but it runs without any problems after pulling the last commits 👍
